// TypeScript interfaces for frktl-website
// Generated by T02

export type VisualKey =
  | "triso"
  | "block"
  | "reactor"
  | "sco2"
  | "factory"
  | "shipping"
  | "quality"
  | "roadmap"
  | "facilities"
  | "testing"
  | null;

export interface Section {
  id: string;
  tag: string;
  accent: string; // CSS var string, e.g. "var(--color-cyan)"
  visual: VisualKey;
  title: string;
  body: string; // Multi-paragraph, \n\n separated
}

export interface Stat {
  value: string;
  unit: string; // Empty string if no unit
  label: string;
}

export interface ComparisonRow {
  feature: string;
  lwr: string; // Traditional LWR column
  frktl: string; // FRKTL HTGR column (the highlighted column)
  solar: string; // Solar + Battery column
}

export interface ComparisonTable {
  headers: [string, string, string, string];
  rows: ComparisonRow[];
  footnote: string;
}

export interface LearningCurveCard {
  unit: string; // e.g. "Unit 1–2"
  phase: string; // e.g. "FOAK"
  desc: string;
  color: string; // CSS var string
}

// SVG component props (used by T03)
export interface SVGIllustrationProps {
  animate: boolean;
}

export interface RoadmapSVGProps extends SVGIllustrationProps {
  activePhase: number; // 0–4
}
